// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS/macOS.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSJpyzPfppxB7GcdwhL925otys-AELFXI',
    appId: '1:457058293252:web:0b9deac4260469aa764751',
    messagingSenderId: '457058293252',
    projectId: 'drive-score-8f564',
    authDomain: 'drive-score-8f564.firebaseapp.com',
    storageBucket: 'drive-score-8f564.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoa-n1gwh2BW0ZFaWJvxby22n2J5GzfOM',
    appId: '1:457058293252:android:1ea29372c404ab2b764751',
    messagingSenderId: '457058293252',
    projectId: 'drive-score-8f564',
    storageBucket: 'drive-score-8f564.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSJpyzPfppxB7GcdwhL925otys-AELFXI',
    appId: '1:457058293252:web:673b34301d63571e764751',
    messagingSenderId: '457058293252',
    projectId: 'drive-score-8f564',
    authDomain: 'drive-score-8f564.firebaseapp.com',
    storageBucket: 'drive-score-8f564.firebasestorage.app',
  );
}
